# Generated by Django 2.1 on 2018-11-25 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('disponible', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Efectivo Disponible')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_venta_real', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_vencimiento', models.DateField(null=True, verbose_name='Fecha de vencimiento')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de venta')),
                ('referencia_ubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Referencia de Ubicacion')),
                ('minimo_permitido', models.IntegerField(verbose_name='Cantidad minima permitida')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.Marca')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.PresentacionProducto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Seleccionar Tipo'), (1, 'Debito'), (2, 'Credito')], default=0)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='inventario.Caja')),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='inventario.Compra')),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='consultas.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VisitaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('anotaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado'), (3, 'Atendido')], default=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inventario.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='inventario.Venta'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='inventario.Lote'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='inventario.Venta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='inventario.Proveedor'),
        ),
    ]
