# Generated by Django 2.1 on 2018-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
