# Generated by Django 2.1 on 2018-11-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20181125_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='caja',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
