# Generated by Django 2.1 on 2018-11-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181127_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='venta',
        ),
    ]
