# Generated by Django 2.1 on 2018-11-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_venta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='cantidad',
            new_name='cantidad_comprada',
        ),
        migrations.AddField(
            model_name='lote',
            name='existencia_actual',
            field=models.IntegerField(default=0),
        ),
    ]
