# Generated by Django 2.1 on 2018-12-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_transaccion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='existencia_actual',
        ),
    ]
