# Generated by Django 2.1.2 on 2018-12-04 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_lote_existencia_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
