# Generated by Django 2.1 on 2018-12-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20181204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora_creacion',
            field=models.DateTimeField(),
        ),
    ]
