# Generated by Django 2.1 on 2018-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20181206_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
