# Generated by Django 2.1 on 2018-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'vendedor')], default=0, verbose_name='tipo de usuario'),
        ),
    ]
