# Generated by Django 2.1 on 2018-11-25 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('latidos_minuto', models.SmallIntegerField(blank=True, null=True, verbose_name='Latidos por Minuto')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nivel_azucar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nivel de Azucar')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diagnostico_enfermedades', models.CharField(blank=True, max_length=500, null=True)),
                ('diagnostico_anotaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('tratamiento_medicamentos', models.CharField(blank=True, max_length=500, null=True)),
                ('tratamiento_anotaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('lugar_origen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar de origen')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de telefono')),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Eliminado')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='consultas.Paciente', verbose_name='Paciente'),
        ),
    ]
